### ISSUE TITLE
Search command bug

### ISSUE THREAD

**Issue by MattCSmith** [MattCSmith/betaBot#1]
searching "woolacombe" seems to cause a promise failure.
Havent found any other words it cant search for

**Comment by thisisabdus** [comment]
Where did you find that word, Matt? 😁😂

**Comment by MattCSmith** [comment]
https://www.google.co.uk/search?q=woolacombe&rlz=1C1CHBF_en-GBGB775GB775&oq=wool&aqs=chrome.1.69i57j35i39j0l4.2303j0j7&sourceid=chrome&ie=UTF-8

Its a place I was heading on holiday too at the time @thisisabdus
